// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeVault.Context;

#nullable disable

namespace TradeVault.Migrations
{
    [DbContext(typeof(TradeVaultContext))]
    [Migration("20250402215131_Seed_Coins")]
    partial class Seed_Coins
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeVault.Models.Candle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CoinId")
                        .HasColumnType("int");

                    b.Property<decimal>("EndPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("TimeSpan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoinId");

                    b.ToTable("Candles");
                });

            modelBuilder.Entity("TradeVault.Models.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Symbol = "btc"
                        },
                        new
                        {
                            Id = 2,
                            Symbol = "eth"
                        },
                        new
                        {
                            Id = 3,
                            Symbol = "bnb"
                        },
                        new
                        {
                            Id = 4,
                            Symbol = "xrp"
                        },
                        new
                        {
                            Id = 5,
                            Symbol = "ada"
                        },
                        new
                        {
                            Id = 6,
                            Symbol = "sol"
                        },
                        new
                        {
                            Id = 7,
                            Symbol = "dot"
                        },
                        new
                        {
                            Id = 8,
                            Symbol = "matic"
                        },
                        new
                        {
                            Id = 9,
                            Symbol = "doge"
                        },
                        new
                        {
                            Id = 10,
                            Symbol = "ltc"
                        });
                });

            modelBuilder.Entity("TradeVault.Responses.PriceResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriceResponses");
                });

            modelBuilder.Entity("TradeVault.Models.Candle", b =>
                {
                    b.HasOne("TradeVault.Models.Coin", null)
                        .WithMany("Candles")
                        .HasForeignKey("CoinId");
                });

            modelBuilder.Entity("TradeVault.Models.Coin", b =>
                {
                    b.Navigation("Candles");
                });
#pragma warning restore 612, 618
        }
    }
}
